---
- name: remove unneeded audit rules before applying proper rules
  file:
    path: /etc/audit/rules.d
    state: absent

- name: create rules dir
  file:
    path: /etc/audit/rules.d
    state: directory

- name: Apply Audit Rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/audit.d/rules.d
  notify: restart_auditd

