---
- name: restart_auditd
  command: /usr/sbin/service auditd restart
  args:
    warn: no

- name: reboot system
  shell: sleep 3; reboot
  async: 15
  poll: 0

- name: restart sshd
  service:
      name: sshd
      state: restarted

- name: restart sssd
  service:
      name: sssd
      state: restarted

    
- name: dconf update
  command: dconf update

- name: confirm grub2 user cfg
  stat:
      path: /boot/grub2/user.cfg
  register: rhel8stig_grub2_user_cfg
  notify: make grub2 config

- name: make grub2 config
  command: /usr/sbin/grub2-mkconfig --output={{ rhel8stig_grub_cfg_path }}
  when:
      - rhel7stig_grub2_user_cfg.stat.exists
      - not rhel7stig_skip_for_travis
      - not rhel7stig_system_is_container

- name: restart rsyslog
  service:
      name: rsyslog
      state: restarted

- name: "restart {{ rhel8stig_time_service }}"
  service:
      name: "{{ rhel8stig_time_service }}"
      state: restarted